import bcrypt from 'bcryptjs';
const data = {
  links: [
    {
      name: 'Home',
      url: '/',
      alt: '',
      icon: '',
      target: '_blank',
      type: 'navbar',
    },
    {
      name: 'Hot',
      url: '/hot',
      alt: '',
      icon: '',
      target: '_blank',
      type: 'navbar',
    },
    {
      name: 'Incomming',
      url: '/incomming',
      alt: '',
      icon: '',
      target: '_blank',
      type: 'navbar',
    },
    {
      name: 'Blog',
      url: '/blog',
      alt: '',
      icon: '',
      target: '_blank',
      type: 'navbar',
    },
    {
      name: 'About Us',
      url: '/aboutus',
      alt: '',
      icon: '',
      target: '_blank',
      type: 'navbar',
    },
  ],
  users: [
    {
      username: 'booklover',
      email: 'booklover@gmail.com',
      password: bcrypt.hashSync('booklover'),
    },
    {
      username: 'admin',
      email: 'admin',
      password: bcrypt.hashSync('admin'),
    },
  ],
  books: [
    {
      name: 'Hành Tinh Của Một Kẻ Nghĩ Nhiều',
      type: '',
      slug: 'book-1',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image: '/imgs/n.jpg',
      price: '1000',
      countInStock: 10,
      numPage: 200,
      rating: 3,
      numRev: 10,
      des: 'Good stuff',
      caterories: [
        { name: 'Tam ly', order: 1 },
        { name: 'Vien tuong', order: 2 },
      ],
    },
    {
      name: 'Nhà Giả Kim (Tái Bản 2020)',
      type: '',
      slug: 'book-2',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image: '/imgs/n1.webp',
      price: '1000',
      countInStock: 10,
      numPage: 200,
      rating: 5,
      numRev: 10,
      des: 'Good stuff',
      caterories: [
        { name: 'Tam ly', order: 1 },
        { name: 'Ton giao', order: 3 },
      ],
    },
    {
      name: 'Thư Viện Nửa Đêm',
      type: '',
      slug: 'book-3',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image: '/imgs/n2.webp',
      price: '400000',
      countInStock: 10,
      numPage: 200,
      rating: 1,
      numRev: 10,
      des: 'Good stuff',
      caterories: [
        { name: 'Tam ly', order: 1 },
        { name: 'Trinh tham', order: 4 },
      ],
    },
    {
      name: 'Cân bằng cảm xúc cả lúc bão giông',
      type: '',
      slug: 'book-4',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image:
        'https://book365.vn/upload/resize_cache/iblock/2bd/570_490_1/2bd9969831f3589e1859d14b5ec7bd17.jpeg',
      price: '1000000',
      countInStock: 10,
      numPage: 200,
      rating: 1,
      numRev: 10,
      des: 'Good stuff',
      caterories: [{ name: 'Tam ly', order: 1 }],
    },
    {
      name: 'Người Giàu Có Nhất Thành Babylon',
      type: '',
      slug: 'book-5',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image:
        'https://book365.vn/upload/resize_cache/iblock/6d7/570_490_1/6d7fac801463e9c2d998754e77890e3a.jpeg',
      price: '200000',
      countInStock: 10,
      numPage: 200,
      rating: 1,
      numRev: 10,
      des: 'Good stuff',
      caterories: [
        { name: 'Tam ly', order: 1 },
        { name: 'Lich su', order: 5 },
      ],
    },
  ],
};
export default data;
