const data = {
  books: [
    {
      name: 'Hành Tinh Của Một Kẻ Nghĩ Nhiều',
      type: '',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image: '/imgs/n.jpg',
      price: '2000000',
      countInStock: 10,
      numPage: 200,
      rating: 5,
      numRev: 10,
      des: 'Good stuff',
    },
    {
      name: 'Nhà Giả Kim (Tái Bản 2020)',
      type: '',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image: '/imgs/n1.webp',
      price: '2000000',
      countInStock: 10,
      numPage: 200,
      rating: 5,
      numRev: 10,
      des: 'Good stuff',
    },
    {
      name: 'Thư Viện Nửa Đêm',
      type: '',
      PublishYear: '2022',
      author: 'Nguyễn Đoàn Minh Thư',
      image: '/imgs/n2.webp',
      price: '2000000',
      countInStock: 10,
      numPage: 200,
      rating: 5,
      numRev: 10,
      des: 'Good stuff',
    },
  ],
};
export default data;
